schema-version: v2
kind: plugin
metadata:
  name: stackspot-infra-s3-poc
  display-name: stackspot-infra-s3-poc
  description: A proof-of-concept to learn how to create a infra plugin on stackspot edp
  version: 0.0.1
spec:
  type: infra
  compatibility:
    - python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  runtime:
    environment:
      - terraform-1-4
      - aws-cli-2
      - git-2
  repository: https://github.com/breno-hof/learning-stackspot-edp
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Terraform
    - AWS S3
  generates:
    connections:
      - type: aws-s3-conn
        alias: aws-s3-connection-interface
        outputs:
          - from: aws-s3-connection-interface-arn
            to: arn
          - from: aws-s3-connection-interface-bucket_name
            to: bucket_name
  stk-projects-only: false
  app-allowed: false
  inputs:
  - label: Type the name of your bucket
    name: bucket_name
    type: text
    required: true 
    default: Bucket
    pattern: '([A-Z][a-z]+)+'
    help: 'Inform your bucket name (e.g.: Bucket)'
  - label: Should enable force destroy?
    name: force_destroy
    type: bool
    default: true
    required: true
    help: 'Inform whether the force destroy should be enable (e.g.: true or false)'
  