schema-version: v2
kind: plugin
metadata:
  name: stackspot-infra-s3-poc
  display-name: stackspot-infra-s3-poc
  description: A proof-of-concept to learn how to create a infra plugin on stackspot edp
  version: 0.0.1
spec:
  type: infra
  compatibility:
    - python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  runtime:
    environment:
      - terraform-1-4
      - aws-cli-2
      - git-2
  repository: https://github.com/breno-hof/learning-stackspot-edp
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
  generates:
    connections:
      - type: aws-s3-conn
        alias: aws-s3-connection-interface
        outputs:
          - from: aws-s3-connection-interface-arn
            to: arn
          - from: aws-s3-connection-interface-bucket_name
            to: bucket_name
  stk-projects-only: false
  app-allowed: false
  inputs:
  - label: Type the name of your resource
    name: resource
    type: text
    required: true 
    default: Client
    pattern: '([A-Z][a-z]+)+'
    help: 'Inform your resource name (e.g.: Client)'
  - label: Choose the http method of the new endpoint
    name: method
    type: text
    items:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    default: GET
    required: true
    help: 'Inform the method of the endpoint (e.g.: post or delete)'
  